server.servlet.context-path=/uploadapp
spring.application.name=Upload Service

spring.datasource.url=endpointsecret
spring.datasource.username=usernamesecret
spring.datasource.password=passwordsecret
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true

spring.resources.static-locations=classpath:/src/main/resources/static/

#Dynamo DB
dynamodb.vpc-endpoint.id=dynamodbvpcesecret

#SNS
sns.file-upload.topic=fileuploadtopicarnsecret
sns.vpc-endpoint.id=sns.ap-south-1.amazonaws.com

#S3
s3.bucket.vpc-endpoint.id=s3bucketvpcesecret
s3.bucket.name=media-bucket-2024

#Secret Manager
secret-manager.vpc-endpoint.dns=secretsmanager.ap-south-1.amazonaws.com

#Logs
logfile.location=/usr/local/tomcat/webapps/logs/uploadapp.log

#Profile
spring.profiles.active=cloud